const productsData = [
    // ============ HERBS (8 منتجات) ============
    {
        id: 1,
        name_en: "Chamomile Flowers",
        name_ar: "زهر البابونج",
        category: "herbs",
        description_en: "Premium quality chamomile flowers for herbal tea and aromatherapy. Known for its calming properties and sweet apple-like aroma.",
        description_ar: "زهر البابونج عالي الجودة لشاي الأعشاب والعلاج بالروائح. معروف بخصائصه المهدئة ورائحته الشبيهة بالتفاح.",
        fullDescription_en: "Chamomile flowers are one of the most popular herbs worldwide, prized for their gentle, calming effects. The flowers are hand-harvested at peak bloom to preserve their essential oils and active compounds including bisabolol, chamazulene, and flavonoids.",
        healthBenefits_en: "Promotes relaxation and sleep, aids digestion, reduces inflammation, soothes skin conditions, relieves menstrual discomfort.",
        howToUse_en: "Steep 1-2 teaspoons of dried flowers in hot water for 5-10 minutes for tea. Use in bath soaks, skincare products, or as a gentle hair rinse.",
        image: "./images/herbs/chamomile.jpg",
        origin: "Egypt",
        quality: "Export Grade A",
        packaging: "Custom packaging available (25kg bags, 500g retail packs)",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Chamomile",
        featured: true
    },
    {
        id: 2,
        name_en: "Hibiscus Flowers",
        name_ar: "زهر الكركديه",
        category: "herbs",
        description_en: "Dried hibiscus flowers for tea with rich color and health benefits. Tart, cranberry-like flavor and deep red infusion.",
        description_ar: "زهر الكركديه المجفف للشاي بلون غني وفوائد صحية. نكهة حامضة تشبه التوت البري مع منقوع أحمر عميق.",
        fullDescription_en: "Hibiscus sabdariffa flowers are harvested from the calyces of the roselle plant. Our premium hibiscus produces a vibrant crimson infusion with a refreshing tart taste. Rich in vitamin C, anthocyanins, and antioxidants.",
        healthBenefits_en: "Supports heart health, helps lower blood pressure, rich in antioxidants, aids weight management, supports liver health.",
        howToUse_en: "Steep 1-2 tablespoons in hot water for 10-15 minutes. Serve hot or iced with honey or mint. Also used in jams, sauces, and cocktails.",
        image: "./images/herbs/hibiscus.jpg",
        origin: "Egypt",
        quality: "Premium Grade",
        packaging: "Bulk bags (25kg), retail packaging available",
        availability: "Seasonal (October-December)",
        wikipedia: "https://en.wikipedia.org/wiki/Hibiscus_tea",
        featured: true
    },
    {
        id: 3,
        name_en: "Mint Leaves",
        name_ar: "أوراق النعناع",
        category: "herbs",
        description_en: "Dried mint leaves with strong aroma for tea and cooking. Refreshing, cooling sensation with high menthol content.",
        description_ar: "أوراق النعناع المجفف برائحة قوية للشاي والطبخ. شعور منعش وبارد مع محتوى عالي من المنثول.",
        fullDescription_en: "Our peppermint leaves are harvested from the Nile Delta region, known for its fertile soil and ideal growing conditions. The leaves are carefully dried to preserve the essential oils, particularly menthol, which gives mint its characteristic cooling sensation.",
        healthBenefits_en: "Relieves indigestion and nausea, freshens breath, alleviates headaches, clears nasal congestion, improves focus.",
        howToUse_en: "Steep fresh or dried leaves for tea. Use in salads, sauces, teas, and as a garnish. Add to smoothies for freshness.",
        image: "./images/herbs/mint.jpg",
        origin: "Egypt",
        quality: "Grade A",
        packaging: "Various sizes from 100g to 25kg",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Mentha",
        featured: true
    },
    {
        id: 4,
        name_en: "Lemongrass",
        name_ar: "عشب الليمون",
        category: "herbs",
        description_en: "Aromatic lemongrass for tea and Asian cuisine. Citrusy flavor with subtle ginger notes.",
        description_ar: "عشب الليمون العطري للشاي والمطبخ الآسيوي. نكهة حمضية مع لمسات زنجبيل خفيفة.",
        fullDescription_en: "Lemongrass (Cymbopogon citratus) is a tall, perennial grass native to tropical regions. Our Egyptian-grown lemongrass offers intense lemon aroma with earthy undertones, perfect for teas and culinary applications.",
        healthBenefits_en: "Reduces anxiety, lowers cholesterol, aids digestion, has antimicrobial properties, supports detoxification.",
        howToUse_en: "Cut stalks into 2-inch pieces and bruise before adding to teas, soups, and curries. Also used in marinades and stir-fries.",
        image: "./images/herbs/lemongrass.jpg",
        origin: "Egypt",
        quality: "Export Grade",
        packaging: "Fresh-cut bundles or dried cut (500g, 1kg)",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Cymbopogon",
        featured: true
    },
    {
        id: 5,
        name_en: "Sage",
        name_ar: "المريمية",
        category: "herbs",
        description_en: "Dried sage leaves with medicinal properties. Earthy, slightly peppery flavor with pine-like aroma.",
        description_ar: "أوراق المريمية المجففة ذات الخصائص الطبية. نكهة ترابية، حارة قليلاً مع رائحة شبيهة بالصنوبر.",
        fullDescription_en: "Sage (Salvia officinalis) has been used for centuries in traditional medicine and cooking. Our Egyptian sage is hand-harvested from the mountainous regions, offering superior essential oil content and potent medicinal properties.",
        healthBenefits_en: "Improves brain function and memory, reduces inflammation, lowers blood sugar, supports oral health, relieves menopausal symptoms.",
        howToUse_en: "Use fresh or dried in poultry dishes, stuffings, and sauces. Make sage tea by steeping leaves in hot water. Add to butter for pasta sauces.",
        image: "./images/herbs/sage.jpg",
        origin: "Egypt",
        quality: "Premium Quality",
        packaging: "Custom packaging available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Sage",
        featured: true
    },
    {
        id: 6,
        name_en: "Thyme",
        name_ar: "الزعتر",
        category: "herbs",
        description_en: "Wild thyme from Egyptian mountains. Intense aroma with notes of mint, lemon, and earth.",
        description_ar: "زعتر بري من الجبال المصرية. رائحة قوية مع نغمات النعناع والليمون والتراب.",
        fullDescription_en: "Wild thyme (Thymus vulgaris) grows abundantly in the mountainous regions of Egypt, where the Mediterranean climate and rocky soil produce plants with concentrated essential oils and robust flavor.",
        healthBenefits_en: "Powerful antimicrobial and antifungal, relieves coughs and bronchitis, boosts immune system, improves digestion.",
        howToUse_en: "Essential in Mediterranean cuisine—use in marinades, roasted vegetables, meats, and soups. Add to olive oil for dipping bread.",
        image: "./images/herbs/thyme.jpg",
        origin: "Egypt",
        quality: "Wild Harvested",
        packaging: "500g, 1kg bags, bulk options",
        availability: "Limited seasonal harvest",
        wikipedia: "https://en.wikipedia.org/wiki/Thyme",
        featured: true
    },
    {
        id: 7,
        name_en: "Rosemary",
        name_ar: "إكليل الجبل",
        category: "herbs",
        description_en: "Premium rosemary leaves for seasoning. Pine-like fragrance with notes of lemon and pepper.",
        description_ar: "أوراق إكليل الجبل الممتازة للتوابل. رائحة تشبه الصنوبر مع نغمات الليمون والفلفل.",
        fullDescription_en: "Rosemary (Rosmarinus officinalis) is an aromatic evergreen herb with needle-like leaves. Our Egyptian rosemary is cultivated in the optimal Mediterranean climate, producing leaves with high essential oil content and robust flavor.",
        healthBenefits_en: "Improves memory and concentration, stimulates circulation, rich in antioxidants, anti-inflammatory properties.",
        howToUse_en: "Use fresh or dried with roasted meats, potatoes, and vegetables. Infuse in olive oil or vinegar. Add to bread dough.",
        image: "./images/herbs/rosemary.jpg",
        origin: "Egypt",
        quality: "Grade A",
        packaging: "As requested",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Rosemary",
        featured: false
    },
    {
        id: 8,
        name_en: "Basil",
        name_ar: "الريحان",
        category: "herbs",
        description_en: "Holy basil leaves with unique aroma. Sweet, peppery flavor with hints of mint and clove.",
        description_ar: "أوراق الريحان المقدس برائحة فريدة. نكهة حلوة، حارة مع لمسات النعناع والقرنفل.",
        fullDescription_en: "Holy basil (Ocimum sanctum), also known as Tulsi, is considered sacred in many cultures. Our Egyptian-grown basil offers exceptional aromatic compounds and is harvested at peak freshness for maximum potency.",
        healthBenefits_en: "Adaptogenic herb reduces stress, supports adrenal health, balances blood sugar, anti-inflammatory, protects against infection.",
        howToUse_en: "Essential in Italian and Thai cuisine. Use fresh in pesto, salads, and as garnish. Add at end of cooking to preserve flavor.",
        image: "./images/herbs/basil.jpg",
        origin: "Egypt",
        quality: "Organic",
        packaging: "Various packaging available",
        availability: "Seasonal",
        wikipedia: "https://en.wikipedia.org/wiki/Basil",
        featured: false
    },

    // ============ SEEDS (8 منتجات) ============
    {
        id: 9,
        name_en: "Fennel Seeds",
        name_ar: "بذور الشمر",
        category: "seeds",
        description_en: "Aromatic fennel seeds for cooking and medicine. Sweet, licorice-like flavor with digestive benefits.",
        description_ar: "بذور الشمر العطرية للطهي والطب. نكهة حلوة تشبه عرق السوس مع فوائد هضمية.",
        fullDescription_en: "Fennel seeds (Foeniculum vulgare) are harvested from the fennel plant's flowers. Our Egyptian fennel seeds are known for their high essential oil content, particularly anethole, which gives them their characteristic sweet flavor and medicinal properties.",
        healthBenefits_en: "Relieves bloating and indigestion, reduces colic in infants, supports milk production in nursing mothers, freshens breath.",
        howToUse_en: "Chew seeds after meals for digestion. Use in baking, sausages, curries, and teas. Toast to enhance flavor.",
        image: "./images/seeds/fennel.jpg",
        origin: "Egypt",
        quality: "Food Grade",
        packaging: "As per request (25kg bags, 500g retail)",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Fennel",
        featured: true
    },
    {
        id: 10,
        name_en: "Cumin Seeds",
        name_ar: "بذور الكمون",
        category: "seeds",
        description_en: "High-quality cumin seeds with strong aroma. Warm, earthy flavor essential in global cuisines.",
        description_ar: "بذور الكمون عالية الجودة برائحة قوية. نكهة دافئة وترابية أساسية في المأكولات العالمية.",
        fullDescription_en: "Cumin (Cuminum cyminum) is one of the most popular spices worldwide. Our Egyptian cumin is grown in the rich soil of Upper Egypt, producing seeds with exceptional essential oil content and the distinctive warm, earthy aroma that defines this spice.",
        healthBenefits_en: "Aids digestion, rich in iron, may help with weight loss, has antimicrobial properties, supports blood sugar control.",
        howToUse_en: "Toast whole seeds before grinding for maximum flavor. Essential in curries, chili, rice dishes, and spice blends.",
        image: "./images/seeds/cumin.jpg",
        origin: "Egypt",
        quality: "Export Grade",
        packaging: "25kg bags, custom sizes available",
        availability: "In Stock",
        wikipedia: "https://en.wikipedia.org/wiki/Cumin",
        featured: true
    },
    {
        id: 11,
        name_en: "Coriander Seeds",
        name_ar: "بذور الكزبرة",
        category: "seeds",
        description_en: "Whole coriander seeds with citrusy flavor. Warm, nutty, with notes of orange peel.",
        description_ar: "بذور كزبرة كاملة بنكهة حمضية. دافئة، جوزية، مع نغمات قشر البرتقال.",
        fullDescription_en: "Coriander seeds (Coriandrum sativum) are the dried fruit of the cilantro plant. Our Egyptian coriander seeds offer a complex flavor profile—citrusy, slightly sweet, with warm, nutty undertones that enhance a wide variety of dishes.",
        healthBenefits_en: "Supports healthy digestion, may lower blood sugar, rich in antioxidants, antimicrobial properties, reduces anxiety.",
        howToUse_en: "Toast and grind for curries, pickling, and spice blends. Use whole in marinades and breads. Essential in garam masala.",
        image: "./images/seeds/coriander.jpg",
        origin: "Egypt",
        quality: "Premium Quality",
        packaging: "Bulk packaging available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Coriander",
        featured: true
    },
    {
        id: 12,
        name_en: "Sesame Seeds",
        name_ar: "بذور السمسم",
        category: "seeds",
        description_en: "White and black sesame seeds, rich in oil. Nutty flavor that intensifies when toasted.",
        description_ar: "بذور السمسم الأبيض والأسود، غنية بالزيت. نكهة جوزية تزداد قوة عند التحميص.",
        fullDescription_en: "Sesame (Sesamum indicum) is one of the oldest cultivated plants in the world. Our Egyptian sesame seeds are prized for their high oil content and rich, nutty flavor. Available in both white (hulled) and black (unhulled) varieties.",
        healthBenefits_en: "Excellent source of calcium, supports bone health, rich in healthy fats, high in antioxidants, supports hormone balance.",
        howToUse_en: "Toast and sprinkle on salads, stir-fries, and baked goods. Use in tahini, halva, and Asian cuisine. Press for sesame oil.",
        image: "./images/seeds/sesame.jpg",
        origin: "Egypt",
        quality: "Grade A",
        packaging: "25kg, 50kg bags, custom retail packaging",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Sesame",
        featured: true
    },
    {
        id: 13,
        name_en: "Fenugreek Seeds",
        name_ar: "بذور الحلبة",
        category: "seeds",
        description_en: "Fenugreek seeds for medicine and cooking. Bitter, maple-like flavor with powerful health benefits.",
        description_ar: "بذور الحلبة للطب والطهي. نكهة مرة تشبه القيقب مع فوائد صحية قوية.",
        fullDescription_en: "Fenugreek (Trigonella foenum-graecum) seeds have been used for thousands of years in both cooking and traditional medicine. Our Egyptian fenugreek seeds are known for their high saponin content and distinctive maple-like aroma.",
        healthBenefits_en: "Increases milk production in nursing mothers, improves blood sugar control, boosts testosterone, reduces inflammation.",
        howToUse_en: "Soak overnight to reduce bitterness. Use in curries, spice blends, and teas. Sprout for salads. Ground for fenugreek paste.",
        image: "./images/seeds/fenugreek.jpg",
        origin: "Egypt",
        quality: "Export Grade",
        packaging: "Various sizes available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Fenugreek",
        featured: true
    },
    {
        id: 14,
        name_en: "Flax Seeds",
        name_ar: "بذور الكتان",
        category: "seeds",
        description_en: "Brown flax seeds rich in omega-3. Nutty flavor packed with essential nutrients.",
        description_ar: "بذور الكتان البنية الغنية بأوميجا 3. نكهة جوزية مليئة بالعناصر الغذائية الأساسية.",
        fullDescription_en: "Flax seeds (Linum usitatissimum) are one of the richest plant sources of omega-3 fatty acids. Our Egyptian flax seeds are carefully cultivated to maximize their nutritional profile, including lignans, fiber, and essential fatty acids.",
        healthBenefits_en: "Excellent source of omega-3 fatty acids, supports heart health, improves digestion, may reduce cancer risk, balances hormones.",
        howToUse_en: "Grind for maximum nutrient absorption. Add to smoothies, oatmeal, baked goods, and yogurt. Use as egg substitute in vegan baking.",
        image: "./images/seeds/flax.jpg",
        origin: "Egypt",
        quality: "Organic",
        packaging: "1kg, 5kg bags, bulk options",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Flax",
        featured: true
    },
    {
    id: 15,
    name_en: "Dill Seeds",
    name_ar: "بذور الشبت",
    category: "herbs",
    description_en: "Aromatic dill seeds with warm, slightly citrusy flavor reminiscent of caraway. Essential for pickling and European cuisine.",
    description_ar: "بذور الشبت العطرية بنكهة دافئة وحمضية قليلاً تذكرنا بالكراوية. أساسية للتخليل والمطبخ الأوروبي.",
    fullDescription_en: "Dill (Anethum graveolens) is an annual herb in the celery family, native to Southwest Asia and the Mediterranean region. While dill leaves are commonly used as a fresh herb, dill seeds offer an entirely different flavor profile - warm, slightly bitter, with subtle citrus notes reminiscent of caraway seeds. Our Egyptian dill seeds are harvested from mature dill plants grown in the fertile Nile Delta region, where the Mediterranean climate produces seeds with exceptional essential oil content. The seeds are naturally sun-dried to preserve their aromatic compounds, including carvone, which gives them their distinctive flavor. Dill has been cultivated for thousands of years, with evidence of its use in ancient Egyptian medicine and cuisine. The seeds have been found in the tombs of Egyptian pharaohs, highlighting their importance in ancient Egyptian culture. Our premium dill seeds are carefully cleaned, sorted, and graded to ensure uniform size and optimal flavor intensity.",
    healthBenefits_en: "Rich in monoterpenes including carvone and limonene, which have antioxidant and anti-inflammatory properties. Contains calcium and manganese essential for bone health and metabolism. Traditional remedy for digestive issues, including indigestion, flatulence, and colic in infants. May help reduce bad cholesterol levels due to fiber content. Contains flavonoids that support immune function and reduce oxidative stress. Antibacterial properties that may help prevent foodborne illnesses. Traditionally used to freshen breath and promote oral health. May help regulate menstrual cycles and reduce menstrual pain. Rich in iron, supporting healthy blood production. The essential oil has antispasmodic properties, helping to relieve muscle cramps. Traditional medicine uses dill seeds to increase breast milk production in nursing mothers.",
    howToUse_en: "Essential in pickling brines for cucumbers, beets, and other vegetables. Crush or grind for use in breads, particularly rye and sourdough. Add to potato salads, coleslaw, and creamy dressings. Use in Scandinavian and Eastern European cuisine for fish dishes, especially salmon and herring. Incorporate into cheese spreads, dips, and sour cream. Add to sauerkraut and fermented vegetables during preparation. Sprinkle over roasted vegetables, particularly carrots and potatoes. Use in spice blends for meat rubs and marinades. Infuse in vinegar or oil for salad dressings. Add to rice pilafs and grain dishes. Combine with mustard seeds for pickling spice mixes. Chew whole seeds after meals as a natural breath freshener and digestive aid. Use in herbal teas for digestive relief.",
    image: "./images/herbs/dill-seeds.jpg",
    origin: "Egypt (Nile Delta - Beheira and Kafr El Sheikh regions)",
    quality: "Premium Grade A - High Essential Oil Content",
    packaging: "Retail: 50g, 100g, 250g resealable bags. Wholesale: 10kg, 25kg food-grade bags. Custom packaging available for private labels. Vacuum-sealed options for long-term storage.",
    availability: "Harvest: March-May. Available year-round from stored crops.",
    wikipedia: "https://en.wikipedia.org/wiki/Dill",
    featured: true
},
    {
        id: 16,
        name_en: "Sunflower Seeds",
        name_ar: "بذور عباد الشمس",
        category: "seeds",
        description_en: "Premium sunflower seeds for snacks. Mild, nutty flavor with satisfying crunch.",
        description_ar: "بذور عباد الشمس الممتازة للوجبات الخفيفة. نكهة جوزية خفيفة مع قرمشة مرضية.",
        fullDescription_en: "Sunflower seeds (Helianthus annuus) are harvested from the stunning sunflower heads. Our Egyptian sunflower seeds are carefully dried and sorted to ensure uniform size and optimal freshness, rich in vitamin E and selenium.",
        healthBenefits_en: "Excellent source of vitamin E (antioxidant), supports skin health, reduces inflammation, rich in selenium, supports thyroid function.",
        howToUse_en: "Eat raw or roasted as a snack. Add to trail mix, salads, and baked goods. Use sunflower seed butter as nut-free alternative.",
        image: "./images/seeds/sunflower.jpg",
        origin: "Egypt",
        quality: "Grade A",
        packaging: "Bulk bags, retail packs available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Sunflower_seed",
        featured: false
    },

    // ============ SPICES (8 منتجات) ============
    {
        id: 17,
        name_en: "Black Pepper",
        name_ar: "فلفل أسود",
        category: "spices",
        description_en: "Premium black pepper corns. Sharp, pungent flavor with hints of pine and citrus.",
        description_ar: "حبوب الفلفل الأسود الممتازة. نكهة حادة، لاذعة مع لمسات الصنوبر والحمضيات.",
        fullDescription_en: "Black pepper (Piper nigrum) is known as the 'king of spices' and is the world's most traded spice. Our black pepper corns are harvested at peak ripeness and sun-dried to develop their characteristic pungent flavor and aromatic complexity.",
        healthBenefits_en: "Enhances nutrient absorption, particularly curcumin, aids digestion, rich in antioxidants, has anti-inflammatory properties.",
        howToUse_en: "Grind fresh for maximum flavor. Use in virtually all savory dishes, marinades, and spice blends. Essential in pepper grinders.",
        image: "./images/spices/pepper.jpg",
        origin: "Egypt",
        quality: "Grade A",
        packaging: "Various sizes available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Black_pepper",
        featured: true
    },
    {
        id: 18,
        name_en: "Coriander Powder",
        name_ar: "مسحوق الكزبرة",
        category: "spices",
        description_en: "Finely ground coriander powder. Warm, citrusy flavor from freshly ground seeds.",
        description_ar: "مسحوق الكزبرة الناعم. نكهة دافئة، حمضية من البذور المطحونة طازجة.",
        fullDescription_en: "Our coriander powder is ground from premium Egyptian coriander seeds, processed in hygienic facilities to preserve the essential oils and aromatic compounds that give this spice its distinctive warm, citrusy character.",
        healthBenefits_en: "Aids digestion, may help lower blood sugar, rich in antioxidants, antimicrobial properties, supports healthy skin.",
        howToUse_en: "Essential in curries, spice rubs, and marinades. Use in baking, soups, and vegetable dishes. Add to rice for aromatic flavor.",
        image: "./images/spices/coriander-powder.jpg",
        origin: "Egypt",
        quality: "Premium Quality",
        packaging: "1kg, 5kg bags, custom retail",
        availability: "In Stock",
        wikipedia: "https://en.wikipedia.org/wiki/Coriander",
        featured: true
    },
    {
        id: 19,
        name_en: "Turmeric Powder",
        name_ar: "مسحوق الكركم",
        category: "spices",
        description_en: "Pure turmeric powder with vibrant color. Earthy, slightly bitter with peppery undertones.",
        description_ar: "مسحوق كركم نقي بلون نابض. ترابي، مر قليلاً مع نغمات فلفلية.",
        fullDescription_en: "Turmeric (Curcuma longa) is revered in both cooking and traditional medicine for its vibrant golden color and powerful compound curcumin. Our Egyptian turmeric is carefully dried and ground to preserve its color and active compounds.",
        healthBenefits_en: "Powerful anti-inflammatory, rich in antioxidants (curcumin), supports joint health, may improve brain function, supports heart health.",
        howToUse_en: "Use in curries, rice dishes, and golden milk. Combine with black pepper to enhance curcumin absorption. Add to smoothies.",
        image: "./images/spices/turmeric.jpg",
        origin: "Egypt",
        quality: "Export Grade",
        packaging: "Custom packaging available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Turmeric",
        featured: true
    },
    {
        id: 20,
        name_en: "Cinnamon Sticks",
        name_ar: "عود قرفة",
        category: "spices",
        description_en: "Premium cinnamon sticks from Egypt. Sweet, warm flavor from rolled bark quills.",
        description_ar: "أعواد قرفة ممتازة من مصر. نكهة حلوة ودافئة من لفائف لحاء الشجر.",
        fullDescription_en: "Cinnamon is harvested from the inner bark of Cinnamomum trees. Our cinnamon sticks (quills) are carefully peeled, rolled, and dried to preserve their essential oils and characteristic sweet, warm flavor.",
        healthBenefits_en: "May lower blood sugar, anti-inflammatory, rich in antioxidants, supports heart health, has antimicrobial properties.",
        howToUse_en: "Add whole to hot beverages, mulled wine, and poaching liquids. Grind for baking and spice blends. Use in curries and rice dishes.",
        image: "./images/spices/cinnamon.jpg",
        origin: "Egypt",
        quality: "Grade A",
        packaging: "Various sizes available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Cinnamon",
        featured: true
    },
    {
        id: 21,
        name_en: "Cardamom Pods",
        name_ar: "حبات الهيل",
        category: "spices",
        description_en: "Green cardamom pods with intense aroma. Complex flavor with notes of eucalyptus, mint, and citrus.",
        description_ar: "حبات هيل خضراء برائحة قوية. نكهة معقدة مع نغمات الأوكالبتوس والنعناع والحمضيات.",
        fullDescription_en: "Cardamom (Elettaria cardamomum) is one of the world's most expensive spices by weight. Our premium green cardamom pods are hand-picked at peak maturity to ensure maximum essential oil content and the complex, aromatic flavor that makes this spice so prized.",
        healthBenefits_en: "Freshens breath naturally, aids digestion, detoxifies the body, may lower blood pressure, has antimicrobial properties.",
        howToUse_en: "Crush pods lightly to release seeds. Use in chai, coffee, baked goods, and curries. Chew seeds for fresh breath.",
        image: "./images/spices/cardamom.jpg",
        origin: "Egypt",
        quality: "Premium",
        packaging: "500g, 1kg bags, bulk options",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Cardamom",
        featured: true
    },
    {
        id: 22,
        name_en: "Cloves",
        name_ar: "قرنفل",
        category: "spices",
        description_en: "Whole cloves with strong aroma. Intensely pungent, sweet, and warming.",
        description_ar: "قرنفل كامل برائحة قوية. لاذع بشكل مكثف، حلو ودافئ.",
        fullDescription_en: "Cloves are the dried flower buds of the Syzygium aromaticum tree. Our cloves are harvested just before blooming, when they reach their peak essential oil content (particularly eugenol), which gives them their intense, numbing pungency and sweet warmth.",
        healthBenefits_en: "Powerful antimicrobial, relieves tooth pain (eugenol), aids digestion, rich in antioxidants, supports liver health.",
        howToUse_en: "Use whole in hams, pickling, and mulled beverages. Ground in baking, spice blends, and curries. Insert into onions for flavoring.",
        image: "./images/spices/cloves.jpg",
        origin: "Egypt",
        quality: "Export Grade",
        packaging: "Bulk packaging available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Clove",
        featured: true
    },
    {
        id: 23,
        name_en: "Paprika Powder",
        name_ar: "مسحوق الفلفل الأحمر",
        category: "spices",
        description_en: "Sweet paprika powder with vibrant color. Mild, sweet pepper flavor with rich red color.",
        description_ar: "مسحوق فلفل أحمر حلو بلون نابض. نكهة فلفل حلوة خفيفة مع لون أحمر غني.",
        fullDescription_en: "Paprika is made from grinding dried Capsicum annuum peppers. Our sweet paprika offers a vibrant red color and mild, sweet pepper flavor without significant heat, perfect for adding color and depth to dishes.",
        healthBenefits_en: "Rich in vitamin C and A, contains capsaicin (anti-inflammatory), supports eye health, boosts immune system, antioxidant properties.",
        howToUse_en: "Essential in Hungarian goulash, Spanish chorizo, and deviled eggs. Use as garnish for hummus and potatoes. Add to rubs and marinades.",
        image: "./images/spices/paprika.jpg",
        origin: "Egypt",
        quality: "Premium",
        packaging: "Custom packaging available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Paprika",
        featured: false
    },
    {
        id: 24,
        name_en: "Ginger Powder",
        name_ar: "مسحوق الزنجبيل",
        category: "spices",
        description_en: "Pure ginger powder with spicy flavor. Pungent, warm, and slightly sweet.",
        description_ar: "مسحوق زنجبيل نقي بنكهة حارة. لاذع، دافئ، وحلو قليلاً.",
        fullDescription_en: "Ginger (Zingiber officinale) is one of the most widely used spices worldwide. Our ginger powder is made from carefully dried and ground Egyptian ginger rhizomes, preserving the pungent gingerol compounds that give ginger its characteristic spicy kick and health benefits.",
        healthBenefits_en: "Relieves nausea and motion sickness, powerful anti-inflammatory, reduces muscle pain, aids digestion, may lower blood sugar.",
        howToUse_en: "Use in baking (gingerbread, cookies), curries, stir-fries, and teas. Add to smoothies for warming effect. Essential in Asian cuisine.",
        image: "./images/spices/ginger.jpg",
        origin: "Egypt",
        quality: "Grade A",
        packaging: "Various sizes available",
        availability: "Available year-round",
        wikipedia: "https://en.wikipedia.org/wiki/Ginger",
        featured: false
    },
    {
    id: 25,
    name_en: "Dried Parsley",
    name_ar: "البقدونس المجفف",
    category: "herbs",
    description_en: "High-quality dried parsley flakes with fresh, vibrant green color and mild peppery flavor. Essential garnish and seasoning herb.",
    description_ar: "رقائق بقدونس مجفف عالي الجودة بلون أخضر نابض ونكهة فلفلية خفيفة. عشب أساسي للتزيين والتبيل.",
    fullDescription_en: "Parsley (Petroselinum crispum) is one of the most widely used culinary herbs in the world, prized for its fresh, clean flavor and vibrant green color. Originating from the Mediterranean region, parsley has been cultivated in Egypt for millennia, with ancient Egyptians using it both as a culinary herb and for medicinal purposes. Our premium dried parsley is made from the finest Italian flat-leaf parsley variety, grown in the fertile soils of the Nile Delta. The leaves are harvested at peak freshness, typically in the early morning when essential oil content is highest, and carefully dried using advanced low-heat technology that preserves the herb's natural color, flavor, and nutritional profile. Unlike inferior dried parsley that turns yellow-brown and loses its aromatic properties, our product maintains a bright green color and fresh, slightly peppery flavor with subtle notes of grass and citrus. The drying process is carefully monitored to retain volatile oils, including myristicin and apiol, which contribute to parsley's distinctive character and health benefits. Our parsley is then screened to remove stems and foreign material, resulting in consistent, high-quality flakes perfect for culinary applications. Egyptian parsley is recognized globally for its superior color retention and flavor intensity, making it a preferred choice for food manufacturers, restaurants, and home cooks worldwide.",
    healthBenefits_en: "Exceptionally rich in vitamin K - just one tablespoon provides over 70% of daily requirements, essential for blood clotting and bone health. Excellent source of vitamin C, supporting immune function and collagen production. Contains apigenin, a flavonoid with powerful antioxidant and anti-inflammatory properties that may help reduce cancer risk. High in beta-carotene, which the body converts to vitamin A for eye health and immune function. Contains folate, essential for cell division and DNA synthesis, particularly important during pregnancy. Rich in chlorophyll, which may help detoxify the body and neutralize carcinogens. Contains volatile oils including myristicin and apiol with antimicrobial and antifungal properties. Supports kidney health and helps prevent kidney stones due to diuretic properties. May help freshen breath naturally by neutralizing sulfur compounds. Contains iron, supporting healthy blood production and preventing anemia. Traditional medicine uses parsley for urinary tract infections, digestive issues, and menstrual problems. The high antioxidant content helps reduce oxidative stress and inflammation throughout the body.",
    howToUse_en: "Essential as a garnish for almost any savory dish - sprinkle over soups, stews, casseroles, and roasted meats. Add to sauces and gravies for color and fresh flavor. Use in tabbouleh salad as a primary ingredient. Mix into compound butters for steaks, fish, and vegetables. Add to omelets, scrambled eggs, and quiches. Sprinkle over roasted or steamed vegetables before serving. Use in marinades for chicken, fish, and lamb. Add to rice dishes, pilafs, and couscous. Mix into bread dough for herb breads and focaccia. Use in salad dressings and vinaigrettes. Add to pasta dishes, particularly with garlic and olive oil. Sprinkle over potatoes - mashed, roasted, or boiled. Use in Middle Eastern dishes like kibbeh and stuffed vegetables. Add to yogurt-based sauces and dips. Mix with breadcrumbs for coating fish or chicken. Use in herb blends like fines herbes. Rehydrate in warm water before using in dishes where texture matters. Add at the end of cooking to preserve color and fresh flavor.",
    image: "./images/herbs/parsley.jpg",
    origin: "Egypt (Nile Delta - Beheira, Kafr El Sheikh, and Dakahlia regions)",
    quality: "Premium Grade A - Flash-Dried for Color Retention",
    packaging: "Retail: 15g, 30g, 50g, 100g resealable pouches. Food service: 500g, 1kg bags. Industrial: 5kg, 10kg, 25kg food-grade bags. Custom packaging available for private labels and wholesale orders. Vacuum-sealed options for extended shelf life.",
    availability: "Main harvest: November-May. Premium quality available year-round through controlled storage.",
    wikipedia: "https://en.wikipedia.org/wiki/Parsley",
    featured: true
},
{
    id: 26,
    name_en: "Bay Laurel Leaves",
    name_ar: "ورق الغار",
    category: "herbs",
    description_en: "Premium dried bay laurel leaves with intense aromatic fragrance. Essential herb for Mediterranean cuisine, soups, and slow-cooked dishes.",
    description_ar: "أوراق غار مجففة فاخرة برائحة عطرية قوية. عشب أساسي للمطبخ المتوسطي والحساء والأطباق بطيئة الطهي.",
    fullDescription_en: "Bay laurel (Laurus nobilis) is an aromatic evergreen tree native to the Mediterranean region, and its leaves have been prized for thousands of years for their distinctive fragrance and culinary properties. In ancient Greece and Rome, bay leaves were woven into wreaths to crown victorious athletes and poets - the origin of the term 'poet laureate.' Today, bay leaves remain an essential herb in cuisines worldwide, particularly in Mediterranean, French, and Middle Eastern cooking. Our premium bay leaves are hand-harvested from mature laurel trees growing in the coastal regions of Egypt, where the Mediterranean climate produces leaves with exceptional essential oil content. The leaves are carefully dried using traditional methods that preserve their characteristic aroma - a complex blend of eucalyptus, clove, and subtle floral notes with a slightly bitter undertone. Unlike many commercial bay leaves that lose their fragrance quickly, our leaves are harvested at peak maturity and dried slowly to retain their essential oils, including eucalyptol, which gives bay its distinctive camphoraceous scent. The leaves are then hand-sorted to ensure uniform size and perfect condition, with no blemishes or discoloration. Egyptian bay leaves are increasingly recognized in international markets for their superior aromatic intensity and consistent quality.",
    image: "./images/herbs/bay-laurel.jpg",
    origin: "Egypt (Mediterranean coastal regions - Alexandria, Matrouh, and North Sinai)",
    quality: "Premium Grade A - Hand-Selected Whole Leaves",
    packaging: "Retail: 10g, 20g, 30g, 50g resealable pouches. Food service: 100g, 250g, 500g bags. Industrial: 1kg, 5kg, 10kg food-grade bags. Bulk: 20kg cartons for export. Custom packaging available for private labels and wholesale orders. Vacuum-sealed options for extended shelf life and essential oil preservation.",
    availability: "Main harvest: September-December. Premium quality available year-round through controlled storage.",
    wikipedia: "https://en.wikipedia.org/wiki/Laurus_nobilis",
    featured: true
},
{
    id: 27,
    name_en: "Crushed Molokhia ",
    name_ar: "الملوخية الناعمة",
    category: "herbs",
    description_en: "Premium dried crushed molokhia leaves, Egypt's national dish. Finely ground texture with earthy flavor and characteristic silky consistency when cooked.",
    description_ar: "أوراق ملوخية مجففة ناعمة فاخرة، الطبق الوطني المصري. قوام مطحون ناعم بنكهة ترابية وقوام حريري مميز عند الطهي.",
    fullDescription_en: "Molokhia (Corchorus olitorius), also known as Jute Mallow or Egyptian Spinach, is a leafy green that holds a special place in Egyptian culinary heritage dating back to the time of the Pharaohs [citation:7]. Historical evidence suggests that ancient Egyptians cultivated and consumed molokhia, making it one of the oldest cultivated vegetables in human history [citation:6]. Our premium crushed molokhia is made from leaves harvested from the fertile Nile Delta regions of Egypt, where the rich soil and optimal climate produce plants with exceptional quality. The leaves are carefully hand-picked at peak freshness, then sun-dried using traditional methods that preserve their vibrant dark green color and nutritional profile. The dried leaves are then finely crushed to create a uniform texture that rehydrates quickly during cooking [citation:4]. Unlike spinach, molokhia develops a unique mucilaginous (silky) consistency when cooked, similar to okra, which is highly prized in Egyptian cuisine [citation:1]. This characteristic texture is what makes authentic molokhia soup so distinctive and beloved. The name 'molokhia' is believed to be derived from 'Molokia', meaning 'for royalty', reflecting its esteemed status in ancient Egyptian culture where it was considered a dish fit for kings [citation:2]. Today, it remains the national dish of Egypt and is cherished throughout the Middle East [citation:7]. Our crushed molokhia undergoes rigorous quality control to ensure 99% purity, moisture content below 8%, and complete absence of foreign materials, stems, or stones [citation:10]. The final product maintains its nutritional integrity and authentic Egyptian flavor profile.",
    healthBenefits_en: "Exceptionally rich in iron, making it valuable for preventing anemia and supporting healthy blood production [citation:6]. High in Vitamin A (beta-carotene) essential for eye health, immune function, and skin maintenance. Excellent source of Vitamin C, a powerful antioxidant that supports collagen production and immune defense. Contains significant amounts of potassium, which helps regulate blood pressure and supports cardiovascular health. Rich in Vitamin B6, important for brain development and function, as well as for maintaining healthy nerves. Good source of calcium for bone health and magnesium for muscle function and energy production [citation:6]. Contains dietary fiber that supports digestive health and promotes feelings of fullness. The mucilaginous properties (soluble fiber) can help soothe the digestive tract and may aid in managing cholesterol levels. Rich in antioxidants including flavonoids and phenolic compounds that help protect cells from oxidative stress and inflammation. Traditional Egyptian medicine has long valued molokhia for its nourishing properties and ability to strengthen the body. The leaves contain chlorophyll, which may help with detoxification and has been studied for its potential anti-inflammatory effects. Low in calories yet nutrient-dense, making it an excellent addition to healthy diets [citation:6]. The combination of vitamins A, C, and E provides comprehensive antioxidant protection throughout the body.",
    image: "./images/herbs/molokhia-crushed.jpg",
    origin: "Egypt (Nile Delta regions - Beheira, Gharbia, and Dakahlia governorates)",
    quality: "Premium Grade A - 99% Purity, Finely Crushed",
    packaging: "Retail: 100g, 200g, 250g, 500g resealable vacuum pouches. Food service: 1kg, 2kg, 5kg bags. Wholesale/Industrial: 10kg, 20kg, 25kg food-grade polypropylene bags. Bulk: 50lb (22.7kg) boxes for commercial use [citation:10]. Custom packaging available for private labels including branded retail pouches with traditional Egyptian designs. Vacuum-sealed options for extended shelf life and freshness preservation.",
    availability: "Year-round availability from stored dried product. Fresh harvest season: April-June.",
    wikipedia: "https://en.wikipedia.org/wiki/Mulukhiyah",
    featured: true
},
{
    id: 28,
    name_en: "Marjoram (Sweet Marjoram)",
    name_ar: "البردقوش",
    category: "herbs",
    description_en: "Premium dried marjoram leaves with sweet, delicate floral aroma and subtle pine-citrus notes. Aromatic herb essential in Mediterranean cuisine and traditional medicine.",
    description_ar: "أوراق بردقوش مجففة فاخرة برائحة زهرية حلوة delicate ونفحات صنوبر وحمضيات خفيفة. عشب عطري أساسي في المطبخ المتوسطي والطب التقليدي.",
    fullDescription_en: "Marjoram (Origanum majorana), also known as sweet marjoram or knotty marjoram, is a aromatic herb belonging to the mint family (Lamiaceae) and is closely related to oregano. Native to the Mediterranean region and parts of Western Asia, marjorah has been cultivated for thousands of years, with ancient Egyptians, Greeks, and Romans valuing it for both culinary and medicinal purposes. The name 'marjoram' is derived from the Latin 'maiorana', and in ancient Egypt, it was used in healing preparations and as a sacred herb. Our premium marjoram is cultivated in the fertile soils of Egypt, particularly in the Nile Delta region, where the Mediterranean climate produces plants with exceptional essential oil content. The leaves are hand-harvested at peak flowering, then carefully dried using low-temperature methods to preserve their delicate aromatic compounds, including terpinene, sabinene, and linalool, which give marjoram its distinctive sweet, floral fragrance with subtle notes of pine and citrus. Unlike oregano, which has a stronger, more pungent flavor, marjoram offers a gentler, more nuanced taste profile that enhances rather than dominates dishes. Our marjoram undergoes rigorous quality control, with testing for essential oil content (minimum 1.5%), moisture levels (below 10%), and microbial safety, ensuring a product of consistent quality that meets international export standards.",
    image: "./images/herbs/marjoram.jpg",
    origin: "Egypt (Nile Delta regions - Beheira, Gharbia, and Qalyubia governorates)",
    quality: "Premium Grade A - Hand-Harvested, Low-Temperature Dried",
    packaging: "Retail: 20g, 40g, 50g, 100g resealable pouches with UV protection. Food service: 250g, 500g, 1kg bags. Industrial: 5kg, 10kg, 20kg food-grade polypropylene bags. Bulk: 25kg cartons for export. Custom packaging available for private labels including branded retail packaging with traditional Egyptian designs. Vacuum-sealed options for extended shelf life and essential oil preservation.",
    availability: "Main harvest: April-June. Premium quality available year-round from stored dried product.",
    wikipedia: "https://en.wikipedia.org/wiki/Marjoram",
    featured: true
},
{
    id: 29,
    name_en: "Black Seed (Nigella Sativa)",
    name_ar: "حبة البركة",
    category: "seeds",
    description_en: "Premium Egyptian Nigella sativa seeds, also known as black cumin or black seed. Small triangular seeds with a nutty, peppery flavor and rich historical significance.",
    description_ar: "بذور حبة البركة المصرية الفاخرة، تُعرف أيضًا بالكمون الأسود أو الحبة السوداء. بذور مثلثة صغيرة بنكهة جوزية فلفلية وأهمية تاريخية غنية.",
    fullDescription_en: "Nigella sativa, commonly known as black seed or black cumin, is an annual flowering plant belonging to the buttercup family (Ranunculaceae), native to Southwest Asia and the Mediterranean region [citation:10]. Our premium Nigella seeds are cultivated in the newly reclaimed lands of Egypt, particularly in Minya Governorate and South Sinai, where research has shown optimal conditions for producing high-quality seeds with superior essential oil content [citation:3]. The plant produces delicate blue or white flowers that develop into spiky seed capsules containing the characteristic small, matte black, triangular-shaped seeds [citation:2]. These seeds have been treasured for thousands of years, with a remarkable history dating back to ancient Egypt. Tutankhamun's tomb contained black seeds, highlighting their importance in Egyptian culture [citation:8]. The first-century Greek physician Dioscorides recorded their medicinal uses, and Hippocrates valued them for treating digestive disorders [citation:8]. In Islamic tradition, Prophet Muhammad described black seed as 'a remedy for all diseases except death' [citation:1]. Today, Egyptian Nigella seeds are recognized globally for their exceptional quality, high thymoquinone content, and potent therapeutic properties. Our seeds are carefully harvested, cleaned, and sorted to ensure uniform size, purity, and maximum potency of bioactive compounds including thymoquinone, thymol, and carvacrol.",
    image: "./images/seeds/nigella-sativa.jpg",
    origin: "Egypt (Minya Governorate - Western Desert hinterland, and South Sinai Governorate) [citation:3]",
    quality: "Premium Grade A - High Thymoquinone Content, Hand-Selected",
    packaging: "Retail:  250g, 500g resealable vacuum pouches with UV protection. Food service: 1kg, 2kg, 5kg bags. Industrial: 10kg, 20kg, 25kg food-grade polypropylene bags. Bulk: 50lb (22.7kg) cartons for export. Custom packaging available for private labels including traditional Egyptian designs. Vacuum-sealed options for extended shelf life and essential oil preservation.",
    availability: "Main harvest: April-June. Premium quality available year-round from stored dried product.",
    wikipedia: "https://en.wikipedia.org/wiki/Nigella_sativa",
    featured: true
},
{
    id: 30,
    name_en: "White Beans ",
    name_ar: "الفاصولياء البيضاء",
    category: "seeds",
    description_en: "Premium Egyptian white beans, also known as fava beans. Creamy texture with mild, nutty flavor. Staple legume in Middle Eastern cuisine.",
    description_ar: "فاصولياء بيضاء مصرية فاخرة، تُعرف أيضًا بالفول الأبيض. قوام كريمي بنكهة جوزية خفيفة. بقول أساسية في المطبخ الشرقي.",
    fullDescription_en: "White beans (Phaseolus vulgaris), also known as fava beans in some regions, are one of the most versatile and nutritious legumes cultivated in Egypt. Our premium white beans are grown in the fertile soils of the Nile Delta, where the rich alluvial deposits and optimal Mediterranean climate produce beans with exceptional quality and flavor. These beans have been a dietary staple in Egyptian cuisine for millennia, with evidence of their cultivation dating back to the time of the Pharaohs [citation:3]. The beans are harvested at peak maturity, then naturally sun-dried to preserve their nutritional value and creamy texture. When cooked, they develop a tender, buttery consistency with a mild, slightly nutty flavor that absorbs surrounding seasonings beautifully. Our white beans undergo rigorous quality control, including cleaning, sorting, and grading to ensure uniform size, color, and optimal moisture content (below 12%). They are free from stones, foreign materials, and insect damage, meeting the highest international export standards. Egyptian white beans are particularly prized in international markets for their superior cooking quality, excellent flavor profile, and consistent performance in various culinary applications.",
    image: "./images/seeds/white-beans.jpg",
    origin: "Egypt (Nile Delta - Beheira, Gharbia, Dakahlia, and Kafr El Sheikh governorates)",
    quality: "Premium Grade A - Hand-Selected, Sun-Dried, Uniform Size",
    packaging: "Retail: 400g, 500g, 1kg resealable vacuum pouches with clear window. Food service: 2kg, 5kg, 10kg polypropylene bags. Industrial: 25kg, 50kg food-grade woven polypropylene bags. Bulk: 1 metric ton (1000kg) jumbo bags for export. Custom packaging available for private labels including branded retail packaging with traditional Egyptian designs. Vacuum-sealed options for extended shelf life and protection against pests. Moisture-proof inner lining available for long-term storage.",
    availability: "Main harvest: March-May. Premium quality available year-round from stored dried product.",
    wikipedia: "https://en.wikipedia.org/wiki/Phaseolus_vulgaris",
    featured: true
},
];